In [1]:
import numpy as np
import pandas as pd

In [2]:
# movie_dataset.csv already contains all movie info including cast, crew and director
movies = pd.read_csv("movie_dataset.csv")

In [3]:
movies.head(1)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron

In [4]:
#movies.head(1)['cast'].values

In [5]:
#movies.head(1)['crew'].values

In [6]:
movies.shape

(4803, 24)

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [8]:
#delete the useless columns
#delete colum expects 
#genres,id,keywords,title,overview,cast,crew,director
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [9]:
#DELETE the useless columns expect which are used for prediction
movies = movies[['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew', 'director']]

In [10]:
# Rename 'id' to 'movie_id' for consistency
movies = movies.rename(columns={'id': 'movie_id'})

In [11]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron

In [12]:
movies.isnull().sum()

movie_id      0
title         0
overview      3
genres       28
keywords    412
cast         43
crew          0
director     30
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
director    0
dtype: int64

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'Action Adventure Fantasy Science Fiction'

In [17]:
MULTI_WORD_GENRES = {
    'Science Fiction': 'ScienceFiction',
    'TV Movie': 'TVMovie',
}

def convert(obj):
    if not isinstance(obj, str):
        return []
    for phrase, replacement in MULTI_WORD_GENRES.items():
        obj = obj.replace(phrase, replacement)
    return obj.split()

In [18]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4795                                         [Drama]
4796               [ScienceFiction, Drama, Thriller]
4798                       [Action, Crime, Thriller]
4800               [Comedy, Drama, Romance, TVMovie]
4802                                   [Documentary]
Name: genres, Length: 4375, dtype: object

In [19]:
movies['genres'] = movies['genres'].apply(convert)

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...",Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...",Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...",Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...",Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[based, on, novel, mars, medallion, space, tra...",Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [22]:
# cast is a plain space-separated string of names, group pairs of words into full names
def convert2(obj):
    if not isinstance(obj, str):
        return []
    words = obj.split()
    names = []
    i = 0
    while i < len(words) and len(names) < 3:
        if i + 1 < len(words):
            names.append(words[i] + words[i + 1])
            i += 2
        else:
            names.append(words[i])
            i += 1
    return names

In [23]:
movies['cast'].apply(convert2)

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2       [DanielCraig, ChristophWaltz, L\u00e9aSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4795      [DarlingNarita, PeterGreene, MichaelNewland]
4796        [ShaneCarruth, DavidSullivan, CaseyGooden]
4798             [CarlosGallardo, Jaimede, HoyosPeter]
4800           [EricMabius, KristinBooth, CrystalLowe]
4802    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4375, dtype: object

In [24]:
movies['cast'] = movies['cast'].apply(convert2)

In [25]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron

In [26]:
# director column is already a plain text string in movie_dataset.csv
# wrap it into a list so it merges cleanly with other list columns
def fetch_director(obj):
    if isinstance(obj, str) and obj.strip():
        return [obj.strip()]
    return []

In [27]:
movies['director'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4795      [Ash Baron-Cohen]
4796        [Shane Carruth]
4798     [Robert Rodriguez]
4800          [Scott Smith]
4802     [Brian Herzlinger]
Name: director, Length: 4375, dtype: object

In [28]:
movies['crew'] = movies['director'].apply(fetch_director)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron],James Cameron
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski],Gore Verbinski
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...","[DanielCraig, ChristophWaltz, L\u00e9aSeydoux]",[Sam Mendes],Sam Mendes
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...","[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan],Christopher Nolan
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[based, on, novel, mars, medallion, space, tra...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton],Andrew Stanton

In [30]:
#convert the overview into the list
movies['overview'] = movies['overview'].apply(lambda x: x.split() if isinstance(x, str) else [])

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron],James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski],Gore Verbinski
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...","[DanielCraig, ChristophWaltz, L\u00e9aSeydoux]",[Sam Mendes],Sam Mendes
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...","[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan],Christopher Nolan
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based, on, novel, mars, medallion, space, tra...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton],Andrew Stanton

In [32]:
#remove the space between the word
movies['overview'] = movies['overview'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['crew'] = movies['crew'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],Gore Verbinski
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...","[DanielCraig, ChristophWaltz, L\u00e9aSeydoux]",[SamMendes],Sam Mendes
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Christopher Nolan
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based, on, novel, mars, medallion, space, tra...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],Andrew Stanton

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,director,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture, clash, future, space, war, space, co...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],James Cameron,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug, abuse, exotic, island, east, ind...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],Gore Verbinski,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based, on, novel, secret, agent, sequel,...","[DanielCraig, ChristophWaltz, L\u00e9aSeydoux]",[SamMendes],Sam Mendes,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc, comics, crime, fighter, terrorist, secret...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Christopher Nolan,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[based, on, novel, mars, medallion, space, tra...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],Andrew Stanton,"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
new_df = movies[['movie_id', 'title', 'tags']].copy()

In [37]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4795,124606,Bang,"[A, young, woman, in, L.A., is, having, a, bad..."
4796,14337,Primer,"[Friends/fledgling, entrepreneurs, invent, a, ..."
4798,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4800,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4802,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [38]:
new_df['tags'].apply(lambda x: " ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4795    A young woman in L.A. is having a bad day: she...
4796    Friends/fledgling entrepreneurs invent a devic...
4798    El Mariachi just wants to play his guitar and ...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4802    Ever since the second grade when he first saw ...
Name: tags, Length: 4375, dtype: object

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [41]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction culture clash future space war space colony society SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [42]:
#convert all into lowercase 
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [43]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

## Vectorization

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [45]:
cv.fit_transform(new_df['tags']).toarray().shape

(4375, 5000)

In [46]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [47]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [49]:
len(cv.get_feature_names_out())

5000

In [50]:
import nltk

In [51]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [52]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [53]:
ps.stem('danced')

'danc'

In [54]:
ps.stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'
)

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [55]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4795    a young woman in l.a. is have a bad day: she' ...
4796    friends/fledgl entrepreneur invent a devic in ...
4798    el mariachi just want to play hi guitar and ca...
4800    "signed, sealed, delivered" introduc a dedic q...
4802    ever sinc the second grade when he first saw h...
Name: tags, Length: 4375, dtype: object

In [56]:
new_df['tags'] = new_df['tags'].apply(stem)

In [57]:
# map the vector and find the distance between them 
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity = cosine_similarity(vectors)

In [59]:
similarity[0]

array([1.        , 0.09847982, 0.06189845, ..., 0.02303267, 0.        ,
       0.        ])

In [60]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(1501, 0.3315938128703508),
 (1872, 0.3285514069160361),
 (456, 0.31583808285461834),
 (92, 0.2913428162916919),
 (298, 0.2909286827258562)]

In [61]:

def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [62]:
recommend('Avatar')

Moonraker
Lifeforce
Lost in Space
Guardians of the Galaxy
Starship Troopers

In [63]:
import pickle

In [64]:
pickle.dump(new_df, open("movies.pkl", 'wb'))

In [65]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'El Mariachi', 'Signed, Sealed, Delivered',
       'My Date with Drew'], dtype=object)

In [66]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [67]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))